services:
  train-env:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rm-detector-train
    # 解决 PyTorch 多线程 DataLoader 报错的核心配置
    shm_size: '8gb'
    stdin_open: true
    tty: true
    # 增加环境变量支持，方便在容器内识别显卡
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    volumes:
      - .:/app
      - ./data:/app/data
      - ./model_res:/app/model_res
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]